package planner

import (
	"strings"
	"time"

	"analysis-support-platform/control-plane/internal/domain"
	"analysis-support-platform/control-plane/internal/id"
	"analysis-support-platform/control-plane/internal/registry"
)

const (
	DatasetFromVersion = "dataset_from_version"
	defaultPlanNotes   = "generated by control-plane scaffold"
)

func BuildDefaultPlan(input domain.AnalysisSubmitRequest) domain.SkillPlan {
	now := time.Now().UTC()
	dataType := "structured"
	if input.DataType != nil && strings.TrimSpace(*input.DataType) != "" {
		dataType = strings.TrimSpace(*input.DataType)
	}
	skills := registry.DefaultPlanSkills(dataType)

	datasetName := DatasetFromVersion
	if input.DatasetName != nil && strings.TrimSpace(*input.DatasetName) != "" {
		datasetName = strings.TrimSpace(*input.DatasetName)
	}

	steps := make([]domain.SkillPlanStep, 0, len(skills))
	for _, skillName := range skills {
		steps = append(steps, domain.SkillPlanStep{
			StepID:      id.New(),
			SkillName:   skillName,
			DatasetName: datasetName,
			Inputs:      defaultInputsForSkill(skillName, input.Goal),
		})
	}

	notes := defaultPlanNotes
	return domain.SkillPlan{
		PlanID:    id.New(),
		Steps:     steps,
		Notes:     &notes,
		CreatedAt: now,
	}
}

func defaultInputsForSkill(skillName, goal string) map[string]any {
	definition, ok := registry.Skill(skillName)
	if !ok {
		return map[string]any{}
	}
	inputs := cloneInputs(definition.DefaultInputs)
	if definition.GoalInput != "" && strings.TrimSpace(goal) != "" {
		inputs[definition.GoalInput] = strings.TrimSpace(goal)
	}
	return inputs
}

func cloneInputs(src map[string]any) map[string]any {
	if len(src) == 0 {
		return map[string]any{}
	}
	cloned := make(map[string]any, len(src))
	for key, value := range src {
		cloned[key] = value
	}
	return cloned
}
